#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-sparkline
Version  : 2.0
Release  : 16
URL      : https://cran.r-project.org/src/contrib/sparkline_2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/sparkline_2.0.tar.gz
Summary  : 'jQuery' Sparkline 'htmlwidget'
Group    : Development/Tools
License  : MIT
Requires: R-htmltools
Requires: R-htmlwidgets
BuildRequires : R-htmltools
BuildRequires : R-htmlwidgets
BuildRequires : R-webshot
BuildRequires : buildreq-R

%description
[![CRAN_Status_Badge](http://www.r-pkg.org/badges/version/sparkline)](https://cran.r-project.org/package=sparkline)

%prep
%setup -q -c -n sparkline
cd %{_builddir}/sparkline

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641127085

%install
export SOURCE_DATE_EPOCH=1641127085
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library sparkline
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library sparkline
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library sparkline
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc sparkline || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sparkline/DESCRIPTION
/usr/lib64/R/library/sparkline/INDEX
/usr/lib64/R/library/sparkline/LICENSE
/usr/lib64/R/library/sparkline/Meta/Rd.rds
/usr/lib64/R/library/sparkline/Meta/features.rds
/usr/lib64/R/library/sparkline/Meta/hsearch.rds
/usr/lib64/R/library/sparkline/Meta/links.rds
/usr/lib64/R/library/sparkline/Meta/nsInfo.rds
/usr/lib64/R/library/sparkline/Meta/package.rds
/usr/lib64/R/library/sparkline/Meta/vignette.rds
/usr/lib64/R/library/sparkline/NAMESPACE
/usr/lib64/R/library/sparkline/R/sparkline
/usr/lib64/R/library/sparkline/R/sparkline.rdb
/usr/lib64/R/library/sparkline/R/sparkline.rdx
/usr/lib64/R/library/sparkline/doc/index.html
/usr/lib64/R/library/sparkline/doc/intro_sparkline.R
/usr/lib64/R/library/sparkline/doc/intro_sparkline.Rmd
/usr/lib64/R/library/sparkline/doc/intro_sparkline.html
/usr/lib64/R/library/sparkline/examples/examples_composite.R
/usr/lib64/R/library/sparkline/examples/examples_dependencies.r
/usr/lib64/R/library/sparkline/examples/examples_dplyr.R
/usr/lib64/R/library/sparkline/examples/sparkline_histogram.R
/usr/lib64/R/library/sparkline/help/AnIndex
/usr/lib64/R/library/sparkline/help/aliases.rds
/usr/lib64/R/library/sparkline/help/paths.rds
/usr/lib64/R/library/sparkline/help/sparkline.rdb
/usr/lib64/R/library/sparkline/help/sparkline.rdx
/usr/lib64/R/library/sparkline/html/00Index.html
/usr/lib64/R/library/sparkline/html/R.css
/usr/lib64/R/library/sparkline/htmlwidgets/lib/jquery.sparkline/README.md
/usr/lib64/R/library/sparkline/htmlwidgets/lib/jquery.sparkline/jquery.sparkline.css
/usr/lib64/R/library/sparkline/htmlwidgets/lib/jquery.sparkline/jquery.sparkline.js
/usr/lib64/R/library/sparkline/htmlwidgets/lib/jquery.sparkline/jquery.sparkline.min.js
/usr/lib64/R/library/sparkline/htmlwidgets/lib/jquery.sparkline/package.json
/usr/lib64/R/library/sparkline/htmlwidgets/lib/jquery/jquery-AUTHORS.txt
/usr/lib64/R/library/sparkline/htmlwidgets/lib/jquery/jquery.min.js
/usr/lib64/R/library/sparkline/htmlwidgets/sparkline.js
/usr/lib64/R/library/sparkline/htmlwidgets/sparkline.yaml
